FROM ubuntu:20.04
RUN apt-get update && apt-get install -y \
    fortune-mod \ 
    cowsay \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . /app
EXPOSE 4499
CMD ["cd /root/myapp","./wisecow.sh"] 
####