name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #enter your docker username
          password: ${{ secrets.DOCKER_PASSWORD }} # enter your docker password

      - name: Build and push Docker image
        run: |
          docker build -t harika232002/myapp:${{ github.sha }} .
          docker push harika232002/myapp:${{ github.sha }}

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.KUBERNETES_HOST }} # enter  your Kubernetes host secret
        username: ${{ secrets.KUBERNETES_USERNAME }} # enter your Kubernetes username secret
        key: ${{ secrets.KUBERNETES_SSH_KEY }} # enter your Kubernetes SSH key secret
        script: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml
          kubectl apply -f clusterissuer.yaml
